Models/EducationViewModel.cs
namespace ProyectoMVC2.Models
{
    public class EducationViewModel
    {
        public string Name { get; set; }
        public string Institution { get; set; }
        public string Description { get; set; }
        public DateTime Start { get; set; }
        public DateTime End { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace ProyectoMVC2.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/ProyectosModelview.cs
namespace ProyectoMVC2.Models
{
    public class ProyectosModelview
    {
        public string Name { get; set; }
        public string Description { get; set;}
        public string category { get; set;}
        public string Image { get; set;}
    }
}

Models/SkillsViewModel.cs
namespace ProyectoMVC2.Models
{
    public class SkillsViewModel
    {
        public string Name { get; set; }
        public int Level { get; set; }

    }
}

Controllers/EducationController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace ProyectoMVC2.Controllers
{
    public class EducationController : Controller
    {
        // GET: EducationController
        public ActionResult Index()
        {
            return View();
        }

        // GET: EducationController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: EducationController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: EducationController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: EducationController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: EducationController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: EducationController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: EducationController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProyectoMVC2.Models;
using System.Diagnostics;

namespace ProyectoMVC2.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            return View();
        }   
        public IActionResult Services()
        {
            return View();
        }
        
        public IActionResult Portfolio()
        {
            return View();
        }
        public IActionResult Contact()
        {
            return View();
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ProyectController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace ProyectoMVC2.Controllers
{
    [Authorize]
    public class ProyectController : Controller
    {
        [AllowAnonymous]
        // GET: ProyectoController
        public ActionResult Index()
        {
            return View();
        }
        [AllowAnonymous]
        // GET: ProyectoController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ProyectoController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ProyectoController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ProyectoController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ProyectoController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ProyectoController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ProyectoController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/SkillController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace ProyectoMVC2.Controllers
{
    [Authorize]
    public class SkillController : Controller
    {
        [AllowAnonymous]
        // GET: SkillController
        public ActionResult Index()
        {
            return View();
        }

        [AllowAnonymous]
        // GET: SkillController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: SkillController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: SkillController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: SkillController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: SkillController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: SkillController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: SkillController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Views/Education/Create.cshtml
@model EducationViewModel

<section class="page-section vh-80 mt-5 bg-dark text-white p-5">
    <h1>Add a new Education</h1>


    <form class="row g-3 needs-validation" novalidate asp-action="Create">

        <partial name="_EducationFormPartialView" model="@Model" />

        <div class="col-12">
            <button class="btn btn-primary" type="submit">Create Education</button>
        </div>

    </form>


    <a class="btn btn-outline-primary m-2" asp-action="Index" asp-controller="Education">Go Back</a>

</section>

Views/Education/Delete.cshtml
<section class="page-section vh-80 mt-5 bg-dark text-white p-5">
    <h1>Deleted with success!!</h1>

    <a class="btn btn-outline-primary m-2" asp-action="Index" asp-controller="Education">Go Back</a>
</section>

Views/Education/Edit.cshtml
@model EducationViewModel

<section class="page-section vh-80 mt-5 bg-dark text-white p-5">
    <h1>Edit Education</h1>


    <form class="row g-3 needs-validation" novalidate asp-action="Edit">

        <partial name="_EducationFormPartialView" model="@Model" />

        <div class="col-12">
            <button class="btn btn-primary" type="submit">Edit Education</button>
        </div>

    </form>


    <a class="btn btn-outline-primary m-2" asp-action="Index" asp-controller="Education">Go Back</a>

</section>

Views/Education/Index.cshtml
@model EducationViewModel;

@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<section class="page-section bg-warning vh-100" id="about">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-lg-8 text-center">
                <h2 class="text-white mt-3">My Studies</h2>
                <hr class="divider divider-light" />
                <p class="text-white-75 mb-4">
                    I´ve been taken several programming courses for becaming the profesional you need to turn your Ideas into Code </>. 
                </p>
                @if (SignInManager.IsSignedIn(User))
                {
                    <a class="btn btn-light btn-xl" asp-area="" asp-controller="Education" asp-action="Create">Add a new education</a>
                }else
                {
                    <a class="btn btn-light btn-xl" asp-area="" asp-controller="Home" asp-action="Contact">Let´s get started</a>
                }
            </div>
        </div>
    </div>
</section>

Views/Home/About.cshtml
<section class="page-section bg-primary vh-100" id="about">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-lg-8 text-center">
                <h2 class="text-white mt-3">Hi, mi name is Marco!</h2>
                <hr class="divider divider-light" />
                <p class="text-white-75 mb-4">I´been working as Developer since January 2023, as Backend developer in .NET at IncluIt and as Web Developer as freelancer. 
                    I´m always traing to improve and become the better version posible of my self for giving my clients the best they can get!</p>
                <a class="btn btn-light btn-xl" asp-area="" asp-controller="Home" asp-action="Contact">Let´s get started</a>
            </div>
        </div>
    </div>
</section>

Views/Home/Contact.cshtml
<!-- Contact-->
<section class="page-section vh-80" id="contact">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-lg-8 col-xl-6 text-center">
                <h2 class="mt-0">Let's Get In Touch!</h2>
                <hr class="divider" />
                <p class="text-muted mb-5">Ready to start your next project? Send me a messages and I´ will get back to you as soon as possible!</p>
            </div>
        </div>
        <div class="row gx-4 gx-lg-5 justify-content-center mb-5">
            <div class="col-lg-6">
                <!-- * * * * * * * * * * * * * * *-->
                <!-- * * SB Forms Contact Form * *-->
                <!-- * * * * * * * * * * * * * * *-->
                <!-- This form is pre-integrated with SB Forms.-->
                <!-- To make this form functional, sign up at-->
                <!-- https://startbootstrap.com/solution/contact-forms-->
                <!-- to get an API token!-->
                <form id="contactForm" data-sb-form-api-token="API_TOKEN">
                    <!-- Name input-->
                    <div class="form-floating mb-3">
                        <input class="form-control" id="name" type="text" placeholder="Enter your name..." data-sb-validations="required" />
                        <label for="name">Full name</label>
                        <div class="invalid-feedback" data-sb-feedback="name:required">A name is required.</div>
                    </div>
                    <!-- Email address input-->
                    <div class="form-floating mb-3">
                        <input class="form-control" id="email" type="email" placeholder="name@example.com" data-sb-validations="required,email" />
                        <label for="email">Email address</label>
                        <div class="invalid-feedback" data-sb-feedback="email:required">An email is required.</div>
                        <div class="invalid-feedback" data-sb-feedback="email:email">Email is not valid.</div>
                    </div>
                    <!-- Phone number input-->
                    <div class="form-floating mb-3">
                        <input class="form-control" id="phone" type="tel" placeholder="(03544)15-629803" data-sb-validations="required" />
                        <label for="phone">Phone number</label>
                        <div class="invalid-feedback" data-sb-feedback="phone:required">A phone number is required.</div>
                    </div>
                    <!-- Message input-->
                    <div class="form-floating mb-3">
                        <textarea class="form-control" id="message" type="text" placeholder="Enter your message here..." style="height: 10rem" data-sb-validations="required"></textarea>
                        <label for="message">Message</label>
                        <div class="invalid-feedback" data-sb-feedback="message:required">A message is required.</div>
                    </div>
                    <!-- Submit success message-->
                    <!---->
                    <!-- This is what your users will see when the form-->
                    <!-- has successfully submitted-->
                    <div class="d-none" id="submitSuccessMessage">
                        <div class="text-center mb-3">
                            <div class="fw-bolder">Form submission successfully send!</div>
                        </div>
                    </div>
                    <!-- Submit error message-->
                    <!---->
                    <!-- This is what your users will see when there is-->
                    <!-- an error submitting the form-->
                    <div class="d-none" id="submitErrorMessage"><div class="text-center text-danger mb-3">Error sending message!</div></div>
                    <!-- Submit Button-->
                    <div class="d-grid"><button class="btn btn-primary btn-xl disabled" id="submitButton" type="submit">Submit</button></div>
                </form>
            </div>
        </div>
    </div>
</section>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<!-- Masthead-->
<header class="masthead">
    <div class="container px-4 px-lg-5 h-100">
        <div class="row gx-4 gx-lg-5 h-100 align-items-center justify-content-center text-center">
            <div class="col-lg-8 align-self-end">
                <h1 class="text-white font-weight-bold">Marco Iannuzzi - Programmer</h1>
                <hr class="divider" />
            </div>
            <div class="col-lg-8 align-self-baseline">
                <p class="text-white-75 mb-5">Let´s work together!</p>
                <a class="btn btn-primary btn-xl" asp-controller="Home" asp-action="About">Who is Marco?</a>
            </div>
        </div>
    </div>
</header>

Views/Home/Portfolio.cshtml
<section class="page-section bg-dark text-white p-5">
    <div class="container text-center">
        <h2 class="text-white pt-5">These are my proyect!</h2>
        <hr class="divider divider-light" />
    </div>
</section>
<div id="portfolio">
    <div class="container-fluid bg-dark">
        <div class="row  g-1">
            <div class="col-lg-4 col-sm-6">
                <a class="portfolio-box" href="~/assets/img/portfolio/fullsize/1.jpg" title="Project Name">
                    <img class="img-fluid" src="~/assets/img/portfolio/thumbnails/1.jpg" alt="..." />
                    <div class="portfolio-box-caption">
                        <div class="project-category text-white-50">Category</div>
                        <div class="project-name">Project Name</div>
                    </div>
                </a>
            </div>
            <div class="col-lg-4 col-sm-6">
                <a class="portfolio-box" href="~/assets/img/portfolio/fullsize/2.jpg" title="Project Name">
                    <img class="img-fluid" src="~/assets/img/portfolio/thumbnails/2.jpg" alt="..." />
                    <div class="portfolio-box-caption">
                        <div class="project-category text-white-50">Category</div>
                        <div class="project-name">Project Name</div>
                    </div>
                </a>
            </div>
            <div class="col-lg-4 col-sm-6">
                <a class="portfolio-box" href="~/assets/img/portfolio/fullsize/3.jpg" title="Project Name">
                    <img class="img-fluid" src="~/assets/img/portfolio/thumbnails/3.jpg" alt="..." />
                    <div class="portfolio-box-caption">
                        <div class="project-category text-white-50">Category</div>
                        <div class="project-name">Project Name</div>
                    </div>
                </a>
            </div>
            <div class="col-lg-4 col-sm-6">
                <a class="portfolio-box" href="~/assets/img/portfolio/fullsize/4.jpg" title="Project Name">
                    <img class="img-fluid" src="~/assets/img/portfolio/thumbnails/4.jpg" alt="..." />
                    <div class="portfolio-box-caption">
                        <div class="project-category text-white-50">Category</div>
                        <div class="project-name">Project Name</div>
                    </div>
                </a>
            </div>
            <div class="col-lg-4 col-sm-6">
                <a class="portfolio-box" href="~/assets/img/portfolio/fullsize/5.jpg" title="Project Name">
                    <img class="img-fluid" src="~/assets/img/portfolio/thumbnails/5.jpg" alt="..." />
                    <div class="portfolio-box-caption">
                        <div class="project-category text-white-50">Category</div>
                        <div class="project-name">Project Name</div>
                    </div>
                </a>
            </div>
            <div class="col-lg-4 col-sm-6">
                <a class="portfolio-box" href="~/assets/img/portfolio/fullsize/6.jpg" title="Project Name">
                    <img class="img-fluid" src="~/assets/img/portfolio/thumbnails/6.jpg" alt="..." />
                    <div class="portfolio-box-caption p-3">
                        <div class="project-category text-white-50">Category</div>
                        <div class="project-name">Project Name</div>
                    </div>
                </a>
            </div>
        </div>
    </div>
</div>
<!-- Call to action-->
<section class="page-section bg-dark text-white">
    <div class="container px-4 px-lg-5 text-center">
        <h2 class="mb-4">Check all my work on my GitHub!</h2>
        <a class="btn btn-light btn-xl" href="https://github.com/Marcoiannuzzi"target="_blank">GitHub</a>
    </div>
</section>

Views/Proyect/Create.cshtml
@model ProyectosModelview

<section class="page-section vh-80 mt-5 bg-dark text-white p-5">
<h1>Create a new Proyect</h1>


<form class="row g-3 needs-validation" novalidate asp-action="Create">

    <partial name="_ProyectFormPartialView" model="@Model"/>

    <div class="col-12">
        <button class="btn btn-primary" type="submit">Create Product</button>
   </div>

</form>


<a class="btn btn-outline-primary m-2" asp-action="Index" asp-controller="Proyect">Go Back</a>

</section>

Views/Proyect/Index.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@model ProyectosModelview


<section class="page-section bg-dark text-white p-5">

    @if(SignInManager.IsSignedIn(User))
    {
        <div class="container text-center">
            <h2 class="text-white pt-5">These are my proyect!</h2>
            <a class="btn btn-primary mt-5" asp-action="Create" asp-controller="Proyect"> Add new proyect </a>
        </div>
    }
    else
    {
        <div class="container text-center">
            <h2 class="text-white pt-5">These are my proyect!</h2>
            <hr class="divider divider-light" />
        </div>
    }
</section>



<div id="portfolio">
    <div class="container-fluid bg-dark">
        <div class="row  g-1">
            <div class="col-lg-4 col-sm-6">
                <a class="portfolio-box" href="~/assets/img/portfolio/fullsize/1.jpg" title="Project Name">
                    <img class="img-fluid" src="~/assets/img/portfolio/thumbnails/1.jpg" alt="..." />
                    <div class="portfolio-box-caption">
                        <div class="project-category text-white-50">Category</div>
                        <div class="project-name">Project Name</div>
                    </div>
                </a>
            </div>
            <div class="col-lg-4 col-sm-6">
                <a class="portfolio-box" href="~/assets/img/portfolio/fullsize/2.jpg" title="Project Name">
                    <img class="img-fluid" src="~/assets/img/portfolio/thumbnails/2.jpg" alt="..." />
                    <div class="portfolio-box-caption">
                        <div class="project-category text-white-50">Category</div>
                        <div class="project-name">Project Name</div>
                    </div>
                </a>
            </div>
            <div class="col-lg-4 col-sm-6">
                <a class="portfolio-box" href="~/assets/img/portfolio/fullsize/3.jpg" title="Project Name">
                    <img class="img-fluid" src="~/assets/img/portfolio/thumbnails/3.jpg" alt="..." />
                    <div class="portfolio-box-caption">
                        <div class="project-category text-white-50">Category</div>
                        <div class="project-name">Project Name</div>
                    </div>
                </a>
            </div>
            <div class="col-lg-4 col-sm-6">
                <a class="portfolio-box" href="~/assets/img/portfolio/fullsize/4.jpg" title="Project Name">
                    <img class="img-fluid" src="~/assets/img/portfolio/thumbnails/4.jpg" alt="..." />
                    <div class="portfolio-box-caption">
                        <div class="project-category text-white-50">Category</div>
                        <div class="project-name">Project Name</div>
                    </div>
                </a>
            </div>
            <div class="col-lg-4 col-sm-6">
                <a class="portfolio-box" href="~/assets/img/portfolio/fullsize/5.jpg" title="Project Name">
                    <img class="img-fluid" src="~/assets/img/portfolio/thumbnails/5.jpg" alt="..." />
                    <div class="portfolio-box-caption">
                        <div class="project-category text-white-50">Category</div>
                        <div class="project-name">Project Name</div>
                    </div>
                </a>
            </div>
            <div class="col-lg-4 col-sm-6">
                <a class="portfolio-box" href="~/assets/img/portfolio/fullsize/6.jpg" title="Project Name">
                    <img class="img-fluid" src="~/assets/img/portfolio/thumbnails/6.jpg" alt="..." />
                    <div class="portfolio-box-caption p-3">
                        <div class="project-category text-white-50">Category</div>
                        <div class="project-name">Project Name</div>
                    </div>
                </a>
            </div>
        </div>
    </div>
</div>
<!-- Call to action-->
<section class="page-section bg-dark text-white">
    <div class="container px-4 px-lg-5 text-center">
        <h2 class="mb-4">Check all my work on my GitHub!</h2>
        <a class="btn btn-light btn-xl" href="https://github.com/Marcoiannuzzi" target="_blank">GitHub</a>
    </div>
</section>

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@{
    ViewData["Title"] = "M.I. - Programmer";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>@ViewData["Title"]</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="~/assets/favicon.ico" />
    <!-- Bootstrap Icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
    <!-- SimpleLightbox plugin CSS-->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.css" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="~/css/styles.css" rel="stylesheet" />
</head>
<body id="page-top">
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-toggleable-lg navbar-light bg-dark fixed-top box-shadow" id="mainNav">
        <div class="container px-4 px-lg-5">
            <a class="navbar-brand text-primary" asp-area="" asp-controller="Home" asp-action="Index">M.I.</a>
            <button class="navbar-toggler  bg-secondary" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto my-2 my-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="About">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Services">Services</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link " asp-area="" asp-controller="Proyect" asp-action="Index">Portfolio</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link " asp-area="" asp-controller="Skill" asp-action="Index">Skills</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link " asp-area="" asp-controller="Education" asp-action="Index">Education</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Contact">Contact</a>
                    </li>
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">Hello @User.Identity?.Name!</a>
                        </li>
                        <li class="nav-item">
                            <form class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                                <button type="submit" class="nav-link btn btn-link">Logout</button>
                            </form>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Identity" asp-page="/Account/Register">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Identity" asp-page="/Account/Login">Login</a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>
    @RenderBody()
    <!-- Footer-->
    <footer class="bg-light py-5">
        <div class="container px-4 px-lg-5"><div class="small text-center text-muted">Copyright &copy; 2023 - Marco Iannuzzi</div></div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- SimpleLightbox plugin JS-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.js"></script>
    <!-- Core theme JS-->
    <script src="~/js/scripts.js"></script>
    <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
    <!-- * *                               SB Forms JS                               * *-->
    <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
    <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
    <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation/dist/additional-methods.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>